name: Deploy Docker Image with Jira

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: jkkimunyi/react_docker:latest

      - name: Update Jira
        run: |
          curl -D- -u jimmy@alluvium.net:${{ secrets.JIRA_API_TOKEN }} \
          -X POST \
          --data '{"body": "Deployment successful"}' \
          -H "Content-Type: application/json" \
          https://jimmykimunyi1.atlassian.net/rest/api/2/issue/SCRUM-1/comment
        env:
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
